import Location from './locations.model.js'

const locations = [
  { name: 'UK', country: 'UK' },
  { name: 'UNITED KINGDOM', country: 'UK' },
  { name: 'ENG', country: 'UK' },
  { name: 'GB', country: 'UK' },
  { name: 'United Kingdom', country: 'UK' },
  { name: 'London', country: 'UK' },
  { name: 'LONDON', country: 'UK' },
  { name: 'Bristol', country: 'UK' },
  { name: 'BRISTOL', country: 'UK' },
  { name: 'Tamworth', country: 'UK' },
  { name: 'TAMWORTH', country: 'UK' },
  { name: 'Brighton', country: 'UK' },
  { name: 'BRIGHTON', country: 'UK' },
  { name: 'England', country: 'UK' },
  { name: 'ENGLAND', country: 'UK' },
  { name: 'Birmingham', country: 'UK' },
  { name: 'BIRMINGHAM', country: 'UK' },
  { name: 'Cambridge', country: 'UK' },
  { name: 'CAMBRIDGE', country: 'UK' },
  { name: 'Manchester', country: 'UK' },
  { name: 'MANCHESTER', country: 'UK' },
  { name: 'Scotland', country: 'UK' },
  { name: 'SCOTLAND', country: 'UK' },
  { name: 'Leeds', country: 'UK' },
  { name: 'LEEDS', country: 'UK' },
  { name: 'Belfast', country: 'UK' },
  { name: 'Liverpool', country: 'UK' },
  { name: 'Newcastle', country: 'UK' },
  { name: 'Warrington', country: 'UK' },
  { name: 'Mayfair', country: 'UK' },
  { name: 'Reading', country: 'UK' },
  { name: 'Salford', country: 'UK' },
  { name: 'Twickenham', country: 'UK' },
  { name: 'Wembley', country: 'UK' },
  { name: 'Southampton', country: 'UK' },
  { name: 'Borough', country: 'UK' },
  { name: 'BOROUGH', country: 'UK' },
  { name: 'US', country: 'US' },
  { name: 'U.S.', country: 'US' },
  { name: 'USA', country: 'US' },
  { name: 'UNITED STATES', country: 'US' },
  { name: 'United States', country: 'US' },
  { name: 'New York', country: 'US' },
  { name: 'NEW YORK', country: 'US' },
  { name: 'Boston', country: 'US' },
  { name: 'BOSTON', country: 'US' },
  { name: 'San Francisco', country: 'US' },
  { name: 'SAN FRANCISCO', country: 'US' },
  { name: 'Washington', country: 'US' },
  { name: 'WASHINGTON', country: 'US' },
  { name: 'Philadelphia', country: 'US' },
  { name: 'PHILADELPHIA', country: 'US' },
  { name: 'Stamford', country: 'US' },
  { name: 'STAMFORD', country: 'US' },
  { name: 'Houston', country: 'US' },
  { name: 'HOUSTON', country: 'US' },
  { name: 'Los Angeles', country: 'US' },
  { name: 'LOS ANGELES', country: 'US' },
  { name: 'Chicago', country: 'US' },
  { name: 'CHICAGO', country: 'US' },
  { name: 'San Diego', country: 'US' },
  { name: 'SAN DIEGO', country: 'US' },
  { name: 'Denver', country: 'US' },
  { name: 'DENVER', country: 'US' },
  { name: 'Salt Lake City', country: 'US' },
  { name: 'SALT LAKE CITY', country: 'US' },
  { name: 'Miami', country: 'US' },
  { name: 'MIAMI', country: 'US' },
  { name: 'Tampa', country: 'US' },
  { name: 'TAMPA', country: 'US' },
  { name: 'Orlando', country: 'US' },
  { name: 'ORLANDO', country: 'US' },
  { name: 'California', country: 'US' },
  { name: 'Radnor', country: 'US' },
  { name: 'Dallas', country: 'US' },
  { name: 'DALLAS', country: 'US' },
  { name: 'Kansas City', country: 'US' },
  { name: 'KANSAS CITY', country: 'US' },
  { name: 'Norman', country: 'US' },
  { name: 'NORMAN', country: 'US' },
  { name: 'Portland', country: 'US' },
  { name: 'PORTLAND', country: 'US' }
]

export const seedLocations = async () => {
  try {
    await Location.deleteMany({}) // Optional: clear the collection before seeding

    await Location.insertMany(locations)

    console.log(locations)
    console.log('Locations seeded successfully')
  } catch (error) {
    console.error('Error seeding locations:', error)
  }
}
